### ISSUE TITLE
你好, 请教openjdk编译问题

### ISSUE THREAD

**Issue by wujichao** [w4123/Mirai-iOS#1]
你好, 打扰了. 我尝试编译https://github.com/w4123/jdk17,  作者大大可否分享下成功编译的脚本, 感谢~~

**Comment by w4123** [comment]
我也记不住当时怎么编译的了，太久以前了，如果有什么错误可以发出来我看一眼。
此外你可以用https://github.com/PojavLauncherTeam/openjdk-multiarch-jdk8u/
这个（或许）会好一点，但是他可能需要JIT。这里的zero的话是不需要JIT的。

**Comment by wujichao** [comment]
感谢大神的回复, pojav那边的我也在看, 那边魔改更多一点, 我现在卡在这里了
猜测是交叉编译的参数设置不对

configure:79225: checking how to run the C preprocessor
configure:79251: /usr/bin/clang -E -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks conftest.c
In file included from conftest.c:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/limits.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/limits.h:63:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/cdefs.h:825:2: error: Unsupported architecture
#error Unsupported architecture
 ^
In file included from conftest.c:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/limits.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/limits.h:64:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/machine/limits.h:11:2: error: architecture not supported
#error architecture not supported
 ^
2 errors generated.
configure:79251: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenJDK"
| #define PACKAGE_TARNAME "openjdk"
| #define PACKAGE_VERSION "openjdk"
| #define PACKAGE_STRING "OpenJDK openjdk"
| #define PACKAGE_BUGREPORT "build-dev@openjdk.java.net"
| #define PACKAGE_URL "http://openjdk.java.net"
| /* end confdefs.h.  */
| #include <limits.h>
| 		     Syntax error




对应的cdefs.h报错的地方在这里, 没有defined(__arm64__) 走到了Unsupported architecture

/*
 * Architecture validation for current SDK
 */
#if   !defined(__sys_cdefs_arch_unknown__) && defined(__arm__)
#elif !defined(__sys_cdefs_arch_unknown__) && defined(__arm64__)
#else
#error Unsupported architecture
#endif

**Comment by w4123** [comment]
他在检测preprocessor的时候没有用传入的extra flags所以他默认给x86_64编译了，我在M1上就不会遇到问题所以没发现。比较简单的解决方式应该是写个简单的clang wrapper内容就是clang -arch arm64然后用它作为CC和CXX。

**Comment by wujichao** [comment]
感谢大神, 我在尝试下

**Comment by wujichao** [comment]
改成 clang -arch arm64 后, hotspot看起来编译成功了. 
但是在后面又报错了. 我是尝试的静态编译, 猜测静态编译的签名好处理一些

报错提示
```
Building target 'static-libs-image' in configuration 'macosx-aarch64-zero-release'
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.incubator.foreign/libsyslookup/static/libsyslookup.a the table of contents is empty (no object file members in the library define global symbols)
Getting symbols from nm
Creating support/native/jdk.attach/libattach/static/libattach.a from 1 file(s)
make[3]: *** [/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.incubator.foreign/libsyslookup/static/libsyslookup.a] Error 1
make[3]: *** Deleting file `/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.incubator.foreign/libsyslookup/static/libsyslookup.a'
make[2]: *** [jdk.incubator.foreign-static-libs] Error 2
make[2]: *** Waiting for unfinished jobs....
Creating support/native/jdk.crypto.cryptoki/libj2pkcs11/static/libj2pkcs11.a from 14 file(s)
Getting symbols from nm
Getting symbols from nm
make[3]: *** [/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.net/libextnet/static/libextnet.a] Error 1
make[3]: *** Deleting file `/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.net/libextnet/static/libextnet.a'
make[2]: *** [jdk.net-static-libs] Error 2
make[3]: *** [/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/java.rmi/librmi/static/librmi.a] Error 1
make[3]: *** Deleting file `/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/java.rmi/librmi/static/librmi.a'
make[2]: *** [java.rmi-static-libs] Error 2
Getting symbols from nm
Getting symbols from nm
make[3]: *** [/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/libjdwp.a] Error 1
make[3]: *** Deleting file `/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/libjdwp.a'
make[2]: *** [jdk.jdwp.agent-static-libs] Error 2
make[3]: *** [/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/java.base/libfdlibm/static/libfdlibm.a] Error 1
make[3]: *** Deleting file `/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/java.base/libfdlibm/static/libfdlibm.a'
make[2]: *** [java.base-static-libs] Error 2
Getting symbols from nm
make[3]: *** [/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.attach/libattach/static/libattach.a] Error 1
make[3]: *** Deleting file `/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.attach/libattach/static/libattach.a'
make[2]: *** [jdk.attach-static-libs] Error 2
Getting symbols from nm
make[3]: *** [/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.crypto.cryptoki/libj2pkcs11/static/libj2pkcs11.a] Error 1
make[3]: *** Deleting file `/Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.crypto.cryptoki/libj2pkcs11/static/libj2pkcs11.a'
make[2]: *** [jdk.crypto.cryptoki-static-libs] Error 2

ERROR: Build failed for target 'static-libs-image' in configuration 'macosx-aarch64-zero-release' (exit code 2) 

```

使用make -n 打印出来的命令 可能相关的如下.
( /bin/rm -f /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/BUILD_LIBJDWP_link.log && /usr/bin/ar -r -cs /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/libjdwp.a /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ArrayReferenceImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ArrayTypeImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ClassLoaderReferenceImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ClassObjectReferenceImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ClassTypeImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/EventRequestImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/FieldImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/FrameID.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/InterfaceTypeImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/MethodImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ModuleReferenceImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ObjectReferenceImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ReferenceTypeImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/SDE.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/StackFrameImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/StringReferenceImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ThreadGroupReferenceImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/ThreadReferenceImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/VirtualMachineImpl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/bag.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/classTrack.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/commonRef.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/debugDispatch.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/debugInit.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/debugLoop.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/error_messages.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/eventFilter.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/eventHandler.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/eventHelper.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/exec_md.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/inStream.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/invoker.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/linker_md.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/log_messages.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/outStream.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/signature.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/standardHandlers.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/stepControl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/stream.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/threadControl.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/transport.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/utf_util.o /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/util.o > >(/usr/bin/tee -a /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/BUILD_LIBJDWP_link.log) 2> >(/usr/bin/tee -a /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/BUILD_LIBJDWP_link.log >&2) || ( exitcode=$? && /bin/cp /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/BUILD_LIBJDWP_link.log /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/make-support/failure-logs/support_native_jdk.jdwp.agent_libjdwp_static_BUILD_LIBJDWP_link.log && /bin/cp /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/support/native/jdk.jdwp.agent/libjdwp/static/BUILD_LIBJDWP_link.cmdline /Users/wujichao/Downloads/tvbox/jdk/miraijdk17build/build/macosx-aarch64-zero-release/make-support/failure-logs/support_native_jdk.jdwp.agent_libjdwp_static_BUILD_LIBJDWP_link.cmdline && exit $exitcode ) )
